# MKDEV 0.11.0 (x-release-please-version)
FROM docker.io/fedora:latest

ARG USERNAME=mkdev

LABEL mkdev.name="rust-fedora" \
      mkdev.summary="Boilerplate with general tools for developing Rust-related projects" \
      mkdev.usage="For more information, see <https://github.com/ttybitnik/mkdev>"

COPY .mkdev/dnf.txt /tmp/
# hadolint ignore=SC2046
RUN dnf update -y && dnf install -y $(cat /tmp/dnf.txt) && dnf clean all \
    && adduser $USERNAME

WORKDIR /home/$USERNAME/workspace

USER $USERNAME

ENV PATH="/home/$USERNAME/.local/bin:$PATH" \
    CARGO_HOME="/home/$USERNAME/.local" \
    RUSTUP_HOME="/home/$USERNAME/.local/share/rustup"

# hadolint ignore=DL4006,SC3040
RUN set -o pipefail && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

COPY --chown=$USERNAME:$USERNAME .mkdev/rustup.txt /tmp/
# hadolint ignore=SC2046
RUN rustup component add $(cat /tmp/rustup.txt)

CMD ["/bin/bash", "-l"]
