# MKDEV 0.9.0 (x-release-please-version)
FROM docker.io/fedora:latest

ARG USERNAME=mkdev

LABEL mkdev.name="omni-fedora" \
      mkdev.summary="Boilerplate with general tools for developing multiple projects" \
      mkdev.usage="For more information, see <https://github.com/ttybitnik/mkdev>"

COPY .mkdev/*.txt /tmp/

RUN dnf update -y && xargs -n 1 dnf install -y < /tmp/dnf.txt && dnf clean all \
    && adduser $USERNAME \
    && chown $USERNAME:$USERNAME /tmp/*.txt

WORKDIR /home/$USERNAME/workspace

USER $USERNAME

ENV PATH="/home/$USERNAME/.local/bin:$PATH"
ENV PATH="/home/$USERNAME/.local/venv/bin:$PATH" \
    GOPATH="/home/$USERNAME/.local/share/go" \
    GOBIN="/home/$USERNAME/.local/bin" \
    NPM_CONFIG_PREFIX="/home/$USERNAME/.local"

RUN xargs -n 1 go install < /tmp/go.txt
RUN python3 -m venv /home/$USERNAME/.local/venv \
    && /home/$USERNAME/.local/venv/bin/pip install --no-cache-dir -r /tmp/pip.txt
RUN xargs -n 1 npm install -g < /tmp/npm.txt && npm cache clean --force

CMD ["/bin/bash", "-l"]
