# MKDEV 0.11.0 (x-release-please-version)
FROM docker.io/fedora:latest

ARG USERNAME=mkdev

LABEL mkdev.name="omni-fedora" \
      mkdev.summary="Boilerplate with general tools for developing multiple projects" \
      mkdev.usage="For more information, see <https://github.com/ttybitnik/mkdev>"

COPY .mkdev/dnf.txt /tmp/
# hadolint ignore=SC2046
RUN dnf update -y && dnf install -y $(cat /tmp/dnf.txt) && dnf clean all \
    && adduser $USERNAME

WORKDIR /home/$USERNAME/workspace

USER $USERNAME

ENV PATH="/home/$USERNAME/.local/bin:$PATH"
ENV PATH="/home/$USERNAME/.local/venv/bin:$PATH" \
    GOPATH="/home/$USERNAME/.local/share/go" \
    GOBIN="/home/$USERNAME/.local/bin" \
    NPM_CONFIG_PREFIX="/home/$USERNAME/.local"

COPY --chown=$USERNAME:$USERNAME .mkdev/go.txt /tmp/
# hadolint ignore=SC2046
RUN go install $(cat /tmp/go.txt)

COPY --chown=$USERNAME:$USERNAME .mkdev/pip.txt /tmp/
RUN python3 -m venv /home/$USERNAME/.local/venv \
    && /home/$USERNAME/.local/venv/bin/pip install --no-cache-dir -r /tmp/pip.txt

COPY --chown=$USERNAME:$USERNAME .mkdev/npm.txt /tmp/
# hadolint ignore=SC2046
RUN npm install -g $(cat /tmp/npm.txt) && npm cache clean --force

CMD ["/bin/bash", "-l"]
