# MKDEV 0.11.0 (x-release-please-version)
FROM docker.io/fedora:latest

ARG USERNAME=mkdev

LABEL mkdev.name="python-fedora" \
      mkdev.summary="Boilerplate with general tools for developing Python-related projects" \
      mkdev.usage="For more information, see <https://github.com/ttybitnik/mkdev>"

COPY .mkdev/dnf.txt /tmp/
RUN dnf update -y && dnf install -y $(cat /tmp/dnf.txt) && dnf clean all \
    && adduser $USERNAME

WORKDIR /home/$USERNAME/workspace

USER $USERNAME

ENV PATH="/home/$USERNAME/.local/bin:$PATH"

COPY --chown=$USERNAME:$USERNAME .mkdev/pip.txt /tmp/
RUN pip3 install --no-cache-dir -r /tmp/pip.txt

CMD ["/bin/bash", "-l"]
