# MKDEV 0.11.0 (x-release-please-version)
FROM docker.io/golang:latest

ARG USERNAME=mkdev

LABEL mkdev.name="go-community" \
      mkdev.summary="Boilerplate with general tools for developing Go-related projects" \
      mkdev.usage="For more information, see <https://github.com/ttybitnik/mkdev>"

COPY .mkdev/apt.txt /tmp/
# hadolint ignore=SC2046
RUN apt-get update && apt-get install --no-install-recommends -y $(cat /tmp/apt.txt) \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && adduser $USERNAME \
    && ln -s /usr/local/go/bin/* /usr/local/bin/

WORKDIR /home/$USERNAME/workspace

USER $USERNAME

ENV PATH="/home/$USERNAME/.local/bin:$PATH" \
    GOPATH=/home/$USERNAME/go \
    GOBIN="/home/$USERNAME/.local/bin"

COPY --chown=$USERNAME:$USERNAME go.mod go.sum ./

COPY --chown=$USERNAME:$USERNAME .mkdev/go.txt /tmp/
# hadolint ignore=SC2046
RUN go install $(cat /tmp/go.txt)
RUN go mod download && go mod verify

CMD ["/bin/bash", "-l"]
