# MKDEV 1.0.0 (x-release-please-version)
FROM docker.io/fedora:latest

ARG USERNAME=mkdev

LABEL mkdev.name="lua-fedora" \
      mkdev.summary="Boilerplate with general tools for developing Lua-related projects" \
      mkdev.usage="For more information, see <https://github.com/ttybitnik/mkdev>"

COPY .mkdev/dnf.txt /tmp/
# hadolint ignore=SC2046
RUN dnf update -y && dnf install -y $(cat /tmp/dnf.txt) && dnf clean all \
    && adduser $USERNAME

WORKDIR /home/$USERNAME/workspace

USER $USERNAME

ENV PATH="/home/$USERNAME/.local/bin:$PATH"

# TODO: Maybe automate the process of updating the release version here.
ADD https://github.com/LuaLS/lua-language-server/releases/download/3.13.5/lua-language-server-3.13.5-linux-x64.tar.gz \
    /home/$USERNAME/.local/bin

CMD ["/bin/bash", "-l"]
