# MKDEV 0.11.0 (x-release-please-version)
FROM docker.io/bash:latest

ARG USERNAME=mkdev

LABEL mkdev.name="bash-community" \
      mkdev.summary="Boilerplate with general tools for developing Bash-related projects" \
      mkdev.usage="For more information, see <https://github.com/ttybitnik/mkdev>"

COPY .mkdev/apk.txt /tmp/
RUN apk add --no-cache $(cat /tmp/apk.txt) \
    && adduser -D $USERNAME

WORKDIR /home/$USERNAME/workspace

USER $USERNAME

ENV PATH="/home/$USERNAME/.local/bin:$PATH" \
    NPM_CONFIG_PREFIX="/home/$USERNAME/.local"

COPY --chown=$USERNAME:$USERNAME .mkdev/npm.txt /tmp/
RUN npm install -g $(cat /tmp/npm.txt) && npm cache clean --force

CMD ["bash", "-l"]
