# MKDEV 1.0.0 (x-release-please-version)
FROM docker.io/fedora:latest

ARG USERNAME=mkdev

LABEL mkdev.name="javascript-fedora" \
      mkdev.summary="Boilerplate with general tools for developing Javascript-related projects" \
      mkdev.usage="For more information, see <https://github.com/ttybitnik/mkdev>"

COPY .mkdev/dnf.txt /tmp/
# hadolint ignore=SC2046
RUN dnf update -y && dnf install -y $(cat /tmp/dnf.txt) && dnf clean all \
    && adduser $USERNAME

WORKDIR /home/$USERNAME/workspace

USER $USERNAME

ENV PATH="/home/$USERNAME/.local/bin:$PATH" \
    NPM_CONFIG_PREFIX="/home/$USERNAME/.local"

COPY --chown=$USERNAME:$USERNAME .mkdev/npm.txt /tmp/
# hadolint ignore=SC2046
RUN npm install -g $(cat /tmp/npm.txt) && npm cache clean --force

CMD ["/bin/bash", "-l"]
