---
failure-threshold: info
ignored:
  - DL3007  # latest (warning)
  - DL3059  # consecutive run (info)
  - DL3048  # label key (style) - bugged thus disabled
label-schema:
  mkdevenv.name: text
  mkdevenv.summary: text
  mkdevenv.usage: text
strict-labels: true
trustedRegistries:
  - docker.io
