# MKDEV 1.0.0 (x-release-please-version)
FROM docker.io/fedora:latest

ARG USERNAME=mkdev

LABEL mkdev.name="haskell-fedora" \
      mkdev.summary="Boilerplate with general tools for developing Haskell-related projects" \
      mkdev.usage="For more information, see <https://github.com/ttybitnik/mkdev>"

COPY .mkdev/dnf.txt /tmp/
# hadolint ignore=SC2046
RUN dnf update -y && dnf install -y $(cat /tmp/dnf.txt) && dnf clean all \
    && adduser $USERNAME

WORKDIR /home/$USERNAME/workspace

USER $USERNAME

ENV PATH="/home/$USERNAME/.local/bin:$PATH" \
    BOOTSTRAP_HASKELL_NONINTERACTIVE=1 \
    BOOTSTRAP_HASKELL_CABAL_XDG=1 \
    BOOTSTRAP_HASKELL_INSTALL_NO_STACK=1 \
    BOOTSTRAP_HASKELL_INSTALL_NO_STACK_HOOK=1 \
    GHCUP_USE_XDG_DIRS=1

# hadolint ignore=DL4006,SC3040
RUN set -o pipefail && curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | bash

COPY --chown=$USERNAME:$USERNAME .mkdev/ghcup.txt /tmp/
# hadolint ignore=SC2046
RUN ghcup install $( cat/tmp/ghcup.txt)

CMD ["/bin/bash", "-l"]
