# MKDEV 0.9.0 (x-release-please-version)
FROM docker.io/haskell:latest

ARG USERNAME=mkdev

LABEL mkdev.name="haskell-community" \
      mkdev.summary="Boilerplate with general tools for developing Haskell-related projects" \
      mkdev.usage="For more information, see <https://github.com/ttybitnik/mkdev>"

COPY .mkdev/*.txt /tmp/

RUN apt-get update && xargs -n 1 apt-get install -y < /tmp/apt.txt \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && adduser $USERNAME \
    && chown $USERNAME:$USERNAME /tmp/*.txt

WORKDIR /home/$USERNAME/workspace

USER $USERNAME

ENV PATH="/home/$USERNAME/.local/bin:$PATH"

RUN cabal update && cabal --version

CMD ["/bin/bash", "-l"]
