# MKDEV 0.7.0 (x-release-please-version)
FROM docker.io/fedora:latest

ARG USERNAME=mkdev

LABEL mkdev.name="fedora-chicken" \
      mkdev.summary="Boilerplate with general tools for developing Chicken-related projects" \
      mkdev.usage="For more information, see <https://github.com/ttybitnik/mkdev>"

COPY .mkdev/*.txt /tmp/

RUN dnf update -y && xargs -n 1 dnf install -y < /tmp/dnf.txt && dnf clean all \
    && adduser $USERNAME \
    && chown $USERNAME:$USERNAME /tmp/*.txt

WORKDIR /home/$USERNAME/workspace

USER $USERNAME

ENV PATH="/home/$USERNAME/.local/bin:$PATH"
ENV CHICKEN_INSTALL_PREFIX="/home/$USERNAME/.local" \
    CHICKEN_INSTALL_REPOSITORY="/home/$USERNAME/.local/lib/chicken/11" \
    CHICKEN_REPOSITORY_PATH="/home/$USERNAME/.local/lib/chicken/11:/usr/lib64/chicken/11"

RUN xargs -n 1 chicken-install < /tmp/chicken.txt

CMD ["/bin/bash", "-l"]
