# MKDEV 0.10.0 (x-release-please-version)
FROM docker.io/fedora:latest

ARG USERNAME=mkdev

LABEL mkdev.name="ansible-fedora" \
      mkdev.summary="Boilerplate with general tools for developing Ansible-related projects" \
      mkdev.usage="For more information, see <https://github.com/ttybitnik/mkdev>"

COPY .mkdev/*.txt /tmp/

RUN dnf update -y && xargs -n 1 dnf install -y < /tmp/dnf.txt && dnf clean all \
    && adduser $USERNAME \
    && mkdir -p /home/$USERNAME/.local/ansible \
    && ln -s /home/$USERNAME/.local/ansible /home/$USERNAME/.ansible \
    && ln -s /usr/bin/podman-remote /usr/bin/podman \
    && chown -R $USERNAME:$USERNAME /tmp/*.txt /home/ttybitnik/.local/

WORKDIR /home/$USERNAME/workspace

USER $USERNAME

ENV PATH="/home/$USERNAME/.local/bin:$PATH"
ENV PATH="/home/$USERNAME/.local/venv/bin:$PATH" \
    NPM_CONFIG_PREFIX="/home/$USERNAME/.local"

RUN python3 -m venv /home/$USERNAME/.local/venv \
    && /home/$USERNAME/.local/venv/bin/pip install --no-cache-dir -r /tmp/pip.txt
RUN xargs -n 1 npm install -g < /tmp/npm.txt && npm cache clean --force

CMD ["/bin/bash", "-l"]
