---
name: SecOps
on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '15 8 * * 4'

jobs:
  trivy:
    permissions:
      contents: read
      security-events: write
      # private repos only
      # actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v5
      - name: Run Trivy vulnerability scanner in fs mode
        id: trivy-scan
        uses: aquasecurity/trivy-action@0.33.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Format and print GH step summary
        if: always()
        run: |
          echo "| Key | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|:--|:--|" >> $GITHUB_STEP_SUMMARY
          echo "| **trivy** | ${{ steps.trivy-scan.outcome }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **trivy_ignore_unfixed** | $TRIVY_IGNORE_UNFIXED  |" >> $GITHUB_STEP_SUMMARY
          echo "| **trivy_severity** | $TRIVY_SEVERITY  |" >> $GITHUB_STEP_SUMMARY
